version: '3.8'

services:
  app:
    build: ./
    command: python main.py
    working_dir: /app
    environment:
      - DVMN_TOKEN=${DVMN_TOKEN}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}